name: Auto Assign Reviewers for PROD

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - feature-tryingNoCodereviewers   # Only trigger when PR targets prod

jobs:
  add_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Add Reviewers
        uses: peter-evans/review-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: |
            uvesh8787-star
            arshadgh
